/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfileSettingsRouteImport } from './routes/_authenticated/profile.settings'
import { Route as AuthenticatedProfileRequestsRouteImport } from './routes/_authenticated/profile.requests'
import { Route as AuthenticatedProfileOrdersRouteImport } from './routes/_authenticated/profile.orders'
import { Route as AuthenticatedProfileDocumentsRouteImport } from './routes/_authenticated/profile.documents'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileRequestsRoute =
  AuthenticatedProfileRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileOrdersRoute =
  AuthenticatedProfileOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileDocumentsRoute =
  AuthenticatedProfileDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/m/$slug': typeof MSlugRoute
  '/profile/documents': typeof AuthenticatedProfileDocumentsRoute
  '/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/profile/requests': typeof AuthenticatedProfileRequestsRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/m/$slug': typeof MSlugRoute
  '/profile/documents': typeof AuthenticatedProfileDocumentsRoute
  '/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/profile/requests': typeof AuthenticatedProfileRequestsRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/m/$slug': typeof MSlugRoute
  '/_authenticated/profile/documents': typeof AuthenticatedProfileDocumentsRoute
  '/_authenticated/profile/orders': typeof AuthenticatedProfileOrdersRoute
  '/_authenticated/profile/requests': typeof AuthenticatedProfileRequestsRoute
  '/_authenticated/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/m/$slug'
    | '/profile/documents'
    | '/profile/orders'
    | '/profile/requests'
    | '/profile/settings'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/m/$slug'
    | '/profile/documents'
    | '/profile/orders'
    | '/profile/requests'
    | '/profile/settings'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/profile'
    | '/m/$slug'
    | '/_authenticated/profile/documents'
    | '/_authenticated/profile/orders'
    | '/_authenticated/profile/requests'
    | '/_authenticated/profile/settings'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/settings': {
      id: '/_authenticated/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthenticatedProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/requests': {
      id: '/_authenticated/profile/requests'
      path: '/requests'
      fullPath: '/profile/requests'
      preLoaderRoute: typeof AuthenticatedProfileRequestsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/orders': {
      id: '/_authenticated/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof AuthenticatedProfileOrdersRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/documents': {
      id: '/_authenticated/profile/documents'
      path: '/documents'
      fullPath: '/profile/documents'
      preLoaderRoute: typeof AuthenticatedProfileDocumentsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileDocumentsRoute: typeof AuthenticatedProfileDocumentsRoute
  AuthenticatedProfileOrdersRoute: typeof AuthenticatedProfileOrdersRoute
  AuthenticatedProfileRequestsRoute: typeof AuthenticatedProfileRequestsRoute
  AuthenticatedProfileSettingsRoute: typeof AuthenticatedProfileSettingsRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileDocumentsRoute: AuthenticatedProfileDocumentsRoute,
  AuthenticatedProfileOrdersRoute: AuthenticatedProfileOrdersRoute,
  AuthenticatedProfileRequestsRoute: AuthenticatedProfileRequestsRoute,
  AuthenticatedProfileSettingsRoute: AuthenticatedProfileSettingsRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
